### ISSUE TITLE
Unable to build with unknown type name 'EVP_MD'

### ISSUE THREAD

**Issue by taco-paco** [libyal/libhmac#6]
https://github.com/libyal/libhmac/blob/a4a49863d50a1fb4adb751f6faddc1b4b5509598/libhmac/libhmac_md5.c#L431

When having `HAVE_LIBCRYPTO`, `HAVE_OPENSSL_EVP_H`, `HAVE_EVP_MD5` defined I'm getting following error during compilation
`error: unknown type name 'EVP_MD'`

This happens because of `#elif` on line [30](https://github.com/libyal/libhmac/blob/a4a49863d50a1fb4adb751f6faddc1b4b5509598/libhmac/libhmac_md5.c#L30). I guess there shall be two consecutive `#if`

```
#if defined( HAVE_LIBCRYPTO ) && defined( HAVE_OPENSSL_MD5_H )
#include <openssl/md5.h>
#endif

#if defined( HAVE_LIBCRYPTO ) && defined( HAVE_OPENSSL_EVP_H )
#include <openssl/err.h>
#include <openssl/evp.h>
#endif
```

**Comment by joachimmetz** [comment]
@taco-paco which version of openssl ?

**Comment by taco-paco** [comment]
1.1.1p
But by the looks of it it also shall replicate on v3.0. I don't see where types.h (contains EVP_MD definition) would be included in `openssl/md5.h`

**Comment by joachimmetz** [comment]
This sounds more like an issue with your build environment.

Can you attach config.log and the actual compile error.

**Comment by taco-paco** [comment]
Sorry for late response. The problem was indeed in my environment. I was enabling simultaneously EVP API & algorithm API
